### ISSUE TITLE
Further font compression

### ISSUE THREAD

**Issue by nathanford** [bramstein/nanofont#4]
Hey Bram. I managed to compress the font files just a bit more. You can grab them from my fork: https://github.com/nathanford/nanofont/tree/master/dist

**Comment by bramstein** [comment]
How did you do that? I don't see any difference between your source file and mine. Do you have some other tool that compresses TrueType files?

**Comment by nathanford** [comment]
Yes. I have a tool for compression, but alas, I cannot share it yet. What were you using?

**Comment by bramstein** [comment]
I'm using ttx to generate the TrueType files and other tools to generate the WOFF and WOFF2. I had a look at your font files in a hex editor and it seems it removes the name table. Unfortunately, that is required for having the fonts display in IE9 and older Opera versions (before the switch to WebKit). I think some older Android WebKit browsers also require it.

**Comment by nathanford** [comment]
I can keep the name table. Let me try that and see if it is any better.

**Comment by nathanford** [comment]
How are you seeing if the name table is there? I am using a hex editor but honestly I have no idea what I am looking for.

**Comment by bramstein** [comment]
You should see `name` somewhere in the ascii view of your hex editor.

**Comment by nathanford** [comment]
Is it necessary to have the font display, though, for these purposes? Managed to get the ttf even smaller, but still no name table. (472b)

**Comment by bramstein** [comment]
Yes, if it doesn't display, the browser will use the fallback font and we won't know which formats are supported.

**Comment by nathanford** [comment]
Right. Ok. Well with the name table I get 520 too. Will keep trying though.
