### ISSUE TITLE
Font doesn't pass OTS in Firefox

### ISSUE THREAD

**Issue by RoelN** [bramstein/nanofont#5]
<img width="1434" alt="nanofont" src="https://cloud.githubusercontent.com/assets/4570664/17829994/183fbb92-66c0-11e6-947f-ed55bedf2ed0.png">

**Comment by bramstein** [comment]
Does this actually fail, or is it just a warning?

**Comment by RoelN** [comment]
It seems to be a warning, otherwise the at-signs would've shown in the black boxes. Some encoding issues in the server issues tripped me up, sorry.

Carry on!
